import type { BillingPrincipalVisualExportDataset } from "@/lib/api/collection-billing-principal";
import {
  formatOspCurrency,
  formatOspPercentage,
  formatOspPercentagePoint,
} from "./billing-principal-report-utils";

export type BillingPrincipalVisualExportKind = "png" | "pdf";

export type BillingPrincipalVisualExportSection = {
  title: string;
  headers: string[];
  rows: string[][];
};

type VisualExportInput = {
  dataset: BillingPrincipalVisualExportDataset;
  signal?: AbortSignal;
};

type RenderRow = {
  cells: string[][];
  height: number;
};

type RenderPage = {
  section: BillingPrincipalVisualExportSection;
  rows: RenderRow[];
  sectionPage: number;
  sectionPages: number;
};

const PAGE_WIDTH = 1_800;
const PAGE_HEIGHT = 1_100;
const PAGE_MARGIN = 48;
const TABLE_TOP = 142;
const TABLE_BOTTOM = PAGE_HEIGHT - 54;
const CELL_PADDING = 8;
const CELL_LINE_HEIGHT = 18;
const CELL_FONT = "14px Arial, sans-serif";
const HEADER_FONT = "700 13px Arial, sans-serif";
const MIN_ROW_HEIGHT = 36;
const MAX_VISUAL_PAGES = 500;

function withAll<T extends { aging: string }, U extends { aging: string }>(
  rows: readonly T[],
  all: U,
): Array<T | U> {
  return [...rows, all];
}

function optional(value: string | number | null | undefined): string {
  return value === null || value === undefined || String(value).trim() === ""
    ? "-"
    : String(value);
}

function money(value: string | null | undefined): string {
  return value === null || value === undefined ? "-" : formatOspCurrency(value);
}

function percentage(value: string | null | undefined): string {
  return value === null || value === undefined ? "-" : formatOspPercentage(value);
}

function percentagePoint(value: string | null | undefined): string {
  return value === null || value === undefined ? "-" : formatOspPercentagePoint(value);
}

function nonEmptyRows(headers: string[], rows: string[][]): string[][] {
  return rows.length > 0 ? rows : [["No data", ...headers.slice(1).map(() => "-")]];
}

export function buildBillingPrincipalVisualExportSections(
  dataset: BillingPrincipalVisualExportDataset,
): BillingPrincipalVisualExportSection[] {
  const { overview } = dataset;
  const revision = overview.revision;
  const sourceLabels = revision.sourceSnapshots
    .map((source) => source.filename
      ? `${source.name} (${source.filename})`
      : source.name)
    .join("; ");
  const metadataRows = [
    ["Target", overview.target.name],
    ["Description", optional(overview.target.description)],
    ["Revision", String(revision.revisionNumber)],
    ["As of", overview.asOf],
    ["Target period", `${revision.from} to ${revision.to}`],
    ["Tracking period", `${revision.trackingStartDate || revision.from} to ${revision.trackingEndDate || revision.to}`],
    ["Aging scope", revision.agingScope.join(", ")],
    ["Nickname scope", revision.nicknameScope.join(", ") || "All permitted nicknames"],
    ["Source snapshots", sourceLabels],
    ["Calendar export range", `${dataset.filters.from} to ${dataset.filters.to}`],
    ["Drilldown date", dataset.filters.date || "All effective dates"],
    ["Generated by", dataset.generatedBy],
    ["Generated", dataset.generatedAt],
  ];

  const systemRows = withAll(overview.systemResult.rows, overview.systemResult.all).map((row) => [
    row.aging,
    money(row.totalOsp),
    percentage(row.targetPercentage),
    money(row.targetOsp),
    money(row.ospClosed),
    percentage(row.resultPercentage),
    row.closedAccountCount.toLocaleString("en-MY"),
  ]);
  const clientRows = withAll(overview.clientResult.rows, overview.clientResult.all).map((row) => [
    row.aging,
    money(row.ospClosed),
    percentage(row.resultPercentage),
    optional(row.effectiveDate),
    optional(row.reference),
    optional(row.note),
  ]);
  const manualSummaryRows = withAll(
    overview.manualReconciliation.rows,
    overview.manualReconciliation.all,
  ).map((row) => [
    row.aging,
    money(row.ospClosed),
    row.closedAccountCount.toLocaleString("en-MY"),
  ]);
  const reconciledRows = withAll(
    overview.reconciledResult.rows,
    overview.reconciledResult.all,
  ).map((row) => [
    row.aging,
    money(row.totalOsp),
    money(row.targetOsp),
    money(row.systemOspClosed),
    money(row.manualReconciledOsp),
    money(row.reconciledOspClosed),
    percentage(row.reconciledResultPercentage),
  ]);

  const manualFinancialRows = dataset.reconciliations.map((row) => [
    row.maskedAccountNumber,
    row.maskedCustomerName,
    row.cardNumberLast4 ? `ending ${row.cardNumberLast4}` : "-",
    row.aging,
    row.status,
    money(row.totalDue),
    money(row.systemEligibleCumulative),
    money(row.manualPriorAmount),
    money(row.reconciledCumulative),
    money(row.billingPrincipalOsp),
    optional(row.reconciledClosedEffectiveDate),
  ]);
  const manualEvidenceRows = dataset.reconciliations.map((row) => [
    row.maskedAccountNumber,
    row.sourceName,
    row.sourceFilename,
    row.callingDate,
    row.asOfDate,
    optional(row.actualPaymentDate),
    optional(row.rawSystemClassification),
    row.reconciledStatus.replace(/_/g, " "),
    row.reason.replace(/_/g, " "),
    String(row.version),
    `${row.updatedAt} by ${row.updatedBy}`,
  ]);
  const manualNotesRows = dataset.reconciliations.map((row) => [
    row.maskedAccountNumber,
    optional(row.reference),
    optional(row.note),
  ]);

  const comparisonResultRows = overview.comparison.rows.map((row) => [
    row.aging,
    percentage(row.systemResultPercentage),
    percentage(row.reconciledResultPercentage),
    percentage(row.clientResultPercentage),
    percentagePoint(row.systemVsClientResultPercentagePointDifference),
    percentagePoint(row.reconciledVsClientResultPercentagePointDifference),
  ]);
  const comparisonOspRows = overview.comparison.rows.map((row) => [
    row.aging,
    money(row.systemOspClosed),
    money(row.manualReconciledOsp),
    money(row.reconciledOspClosed),
    money(row.clientOspClosed),
    money(row.systemVsClientOspDifference),
    money(row.reconciledVsClientOspDifference),
  ]);

  const calendarDailyRows = dataset.calendar.map((day) => [
    day.date,
    day.aging,
    money(day.systemOspClosedToday),
    money(day.manualReconciliationOspClosedToday),
    money(day.reconciledOspClosedToday),
    String(day.systemDailyAccounts),
    String(day.manualDailyAccounts),
    String(day.reconciledDailyAccounts),
  ]);
  const calendarCumulativeRows = dataset.calendar.map((day) => [
    day.date,
    day.aging,
    money(day.totalOsp),
    money(day.targetOsp),
    money(day.systemCumulativeOspClosed),
    money(day.manualReconciliationCumulativeOsp),
    money(day.reconciledCumulativeOspClosed),
    percentage(day.systemResultPercentage),
    percentage(day.reconciledResultPercentage),
    percentage(day.systemPreviousResultPercentage),
    percentage(day.reconciledPreviousResultPercentage),
    percentage(day.clientResultPercentage),
    percentagePoint(day.systemDailyMovementPercentagePoints),
    percentagePoint(day.reconciledDailyMovementPercentagePoints),
    percentage(day.systemAchievementVsTargetPercentage),
    percentage(day.reconciledAchievementVsTargetPercentage),
  ]);

  const drilldownFinancialRows = dataset.drilldown.map((row) => [
    row.maskedAccountNumber,
    row.maskedCustomerName,
    row.cardNumberLast4 ? `ending ${row.cardNumberLast4}` : "-",
    row.contributionSource === "SYSTEM_ABORT_CP" ? "System Abort CP" : "Manual Reconciliation",
    row.aging,
    money(row.totalDue),
    money(row.systemEligibleCumulative),
    money(row.manualPriorAmount),
    money(row.reconciledCumulative),
    money(row.billingPrincipalOsp),
    row.effectiveClosedDate,
  ]);
  const drilldownEvidenceRows = dataset.drilldown.map((row) => [
    row.maskedAccountNumber,
    row.sourceName,
    row.sourceFilename,
    row.callingDate,
    row.effectiveClosedDate,
    optional(row.systemClosureCollectionAmount),
    optional(row.systemClosureStaffNickname),
    optional(row.reason?.replace(/_/g, " ")),
    optional(row.reference),
    optional(row.reconciliationCreatedAt && row.reconciliationCreatedBy
      ? `${row.reconciliationCreatedAt} by ${row.reconciliationCreatedBy}`
      : null),
    optional(row.reconciliationUpdatedAt && row.reconciliationUpdatedBy
      ? `${row.reconciliationUpdatedAt} by ${row.reconciliationUpdatedBy}`
      : null),
  ]);

  return [
    { title: "Metadata", headers: ["Field", "Value"], rows: metadataRows },
    {
      title: "Table A - System Result",
      headers: ["Aging", "TT OSP", "Target %", "Target OSP", "OSP Closed", "Result %", "Accounts"],
      rows: systemRows,
    },
    {
      title: "Table B - Client Result",
      headers: ["Aging", "OSP Closed", "Result %", "Effective Date", "Reference", "Note"],
      rows: clientRows,
    },
    {
      title: "Table C - Manual Reconciliation Summary",
      headers: ["Aging", "Eligible OSP", "Closed Accounts"],
      rows: manualSummaryRows,
    },
    {
      title: "Table C - Account Financial Detail",
      headers: ["Account", "Customer", "Card", "Aging", "Status", "Total Due", "System", "Manual", "Reconciled", "Billing OSP", "Effective Close"],
      rows: nonEmptyRows(["Account", "Customer", "Card", "Aging", "Status", "Total Due", "System", "Manual", "Reconciled", "Billing OSP", "Effective Close"], manualFinancialRows),
    },
    {
      title: "Table C - Evidence and State",
      headers: ["Account", "Source", "Filename", "Calling Date", "As Of", "Payment Date", "System Class", "Reconciled State", "Reason", "Version", "Updated"],
      rows: nonEmptyRows(["Account", "Source", "Filename", "Calling Date", "As Of", "Payment Date", "System Class", "Reconciled State", "Reason", "Version", "Updated"], manualEvidenceRows),
    },
    {
      title: "Table C - Reference and Notes",
      headers: ["Account", "Evidence Reference", "Note"],
      rows: nonEmptyRows(["Account", "Evidence Reference", "Note"], manualNotesRows),
    },
    {
      title: "Table D - Reconciled Internal Result",
      headers: ["Aging", "TT OSP", "Target OSP", "System OSP", "Table C OSP", "Reconciled OSP", "Result %"],
      rows: reconciledRows,
    },
    {
      title: "System vs Client vs Reconciled - Result",
      headers: ["Aging", "System %", "Reconciled %", "Client %", "System-Client pp", "Reconciled-Client pp"],
      rows: comparisonResultRows,
    },
    {
      title: "System vs Client vs Reconciled - OSP",
      headers: ["Aging", "System OSP", "Table C OSP", "Reconciled OSP", "Client OSP", "System-Client", "Reconciled-Client"],
      rows: comparisonOspRows,
    },
    {
      title: "Daily Movement",
      headers: ["Date", "Aging", "System Today", "Table C Today", "Reconciled Today", "System Accounts", "Table C Accounts", "Reconciled Accounts"],
      rows: nonEmptyRows(["Date", "Aging", "System Today", "Table C Today", "Reconciled Today", "System Accounts", "Table C Accounts", "Reconciled Accounts"], calendarDailyRows),
    },
    {
      title: "Cumulative Calendar",
      headers: ["Date", "Aging", "TT OSP", "Target OSP", "System Cum.", "Table C Cum.", "Reconciled Cum.", "System %", "Reconciled %", "System Prev. %", "Reconciled Prev. %", "Client %", "System Move pp", "Reconciled Move pp", "System Achievement", "Reconciled Achievement"],
      rows: nonEmptyRows(["Date", "Aging", "TT OSP", "Target OSP", "System Cum.", "Table C Cum.", "Reconciled Cum.", "System %", "Reconciled %", "System Prev. %", "Reconciled Prev. %", "Client %", "System Move pp", "Reconciled Move pp", "System Achievement", "Reconciled Achievement"], calendarCumulativeRows),
    },
    {
      title: "OSP Closed Drilldown - Financial",
      headers: ["Account", "Customer", "Card", "Source", "Aging", "Total Due", "System", "Manual", "Reconciled", "Billing OSP", "Effective Close"],
      rows: nonEmptyRows(["Account", "Customer", "Card", "Source", "Aging", "Total Due", "System", "Manual", "Reconciled", "Billing OSP", "Effective Close"], drilldownFinancialRows),
    },
    {
      title: "OSP Closed Drilldown - Evidence",
      headers: ["Account", "Source", "Filename", "Calling Date", "Effective Close", "System Closure Amount", "System Staff", "Reason", "Reference", "Created", "Updated"],
      rows: nonEmptyRows(["Account", "Source", "Filename", "Calling Date", "Effective Close", "System Closure Amount", "System Staff", "Reason", "Reference", "Created", "Updated"], drilldownEvidenceRows),
    },
  ];
}

function abortIfRequested(signal?: AbortSignal) {
  if (signal?.aborted) throw new DOMException("The export was cancelled.", "AbortError");
}

function wrapCanvasText(
  context: CanvasRenderingContext2D,
  rawValue: string,
  maximumWidth: number,
  font: string,
): string[] {
  context.font = font;
  const paragraphs = String(rawValue).replace(/\r\n?/g, "\n").split("\n");
  const lines: string[] = [];
  for (const paragraph of paragraphs) {
    const words = paragraph.split(/\s+/u).filter(Boolean);
    if (words.length === 0) {
      lines.push("");
      continue;
    }
    let line = "";
    for (const word of words) {
      const candidate = line ? `${line} ${word}` : word;
      if (context.measureText(candidate).width <= maximumWidth) {
        line = candidate;
        continue;
      }
      if (line) lines.push(line);
      if (context.measureText(word).width <= maximumWidth) {
        line = word;
        continue;
      }
      let part = "";
      for (const character of word) {
        if (part && context.measureText(part + character).width > maximumWidth) {
          lines.push(part);
          part = character;
        } else {
          part += character;
        }
      }
      line = part;
    }
    if (line || words.length > 0) lines.push(line);
  }
  return lines.length > 0 ? lines : [""];
}

function prepareRow(
  context: CanvasRenderingContext2D,
  row: string[],
  columnWidth: number,
  font: string,
): string[][] {
  return row.map((cell) => wrapCanvasText(context, cell, columnWidth - CELL_PADDING * 2, font));
}

function paginateSection(
  context: CanvasRenderingContext2D,
  section: BillingPrincipalVisualExportSection,
): RenderPage[] {
  const tableWidth = PAGE_WIDTH - PAGE_MARGIN * 2;
  const columnWidth = tableWidth / Math.max(1, section.headers.length);
  const headerLines = prepareRow(context, section.headers, columnWidth, HEADER_FONT);
  const headerHeight = Math.max(
    MIN_ROW_HEIGHT,
    Math.max(...headerLines.map((lines) => lines.length)) * CELL_LINE_HEIGHT + CELL_PADDING * 2,
  );
  const capacity = TABLE_BOTTOM - TABLE_TOP - headerHeight;
  const pages: RenderPage[] = [];
  let pageRows: RenderRow[] = [];
  let usedHeight = 0;

  const finishPage = () => {
    pages.push({ section, rows: pageRows, sectionPage: 0, sectionPages: 0 });
    pageRows = [];
    usedHeight = 0;
  };

  for (const row of section.rows) {
    const allLines = prepareRow(context, row, columnWidth, CELL_FONT);
    const lineCount = Math.max(1, ...allLines.map((lines) => lines.length));
    let offset = 0;
    while (offset < lineCount) {
      let availableHeight = capacity - usedHeight;
      let linesThatFit = Math.floor((availableHeight - CELL_PADDING * 2) / CELL_LINE_HEIGHT);
      if (linesThatFit < 1 && pageRows.length > 0) {
        finishPage();
        availableHeight = capacity;
        linesThatFit = Math.floor((availableHeight - CELL_PADDING * 2) / CELL_LINE_HEIGHT);
      }
      if (linesThatFit < 1) throw new Error("The visual export page cannot fit a table row.");
      const take = Math.min(linesThatFit, lineCount - offset);
      const cells = allLines.map((lines, columnIndex) => {
        const slice = lines.slice(offset, offset + take);
        if (offset > 0 && columnIndex === 0 && slice.length > 0) slice[0] = `${slice[0]} (continued)`;
        return slice;
      });
      const height = Math.max(MIN_ROW_HEIGHT, take * CELL_LINE_HEIGHT + CELL_PADDING * 2);
      pageRows.push({ cells, height });
      usedHeight += height;
      offset += take;
      if (offset < lineCount) finishPage();
    }
  }
  if (pageRows.length > 0 || pages.length === 0) finishPage();
  return pages.map((page, index) => ({
    ...page,
    sectionPage: index + 1,
    sectionPages: pages.length,
  }));
}

function buildRenderPages(input: VisualExportInput): RenderPage[] {
  abortIfRequested(input.signal);
  const measurementCanvas = document.createElement("canvas");
  const context = measurementCanvas.getContext("2d");
  if (!context) throw new Error("This browser cannot prepare the report image.");
  try {
    const pages = buildBillingPrincipalVisualExportSections(input.dataset)
      .flatMap((section) => paginateSection(context, section));
    if (pages.length > MAX_VISUAL_PAGES) {
      throw new Error(
        `This visual report requires ${pages.length.toLocaleString()} pages. Narrow the date/aging scope or use Excel so no rows are omitted.`,
      );
    }
    return pages;
  } finally {
    measurementCanvas.width = 1;
    measurementCanvas.height = 1;
  }
}

function drawLines(
  context: CanvasRenderingContext2D,
  lines: string[],
  x: number,
  y: number,
  height: number,
  font: string,
) {
  context.font = font;
  context.fillStyle = "#0f172a";
  const contentHeight = lines.length * CELL_LINE_HEIGHT;
  const startY = y + Math.max(CELL_PADDING, (height - contentHeight) / 2) + CELL_LINE_HEIGHT / 2;
  lines.forEach((line, index) => context.fillText(line, x + CELL_PADDING, startY + index * CELL_LINE_HEIGHT));
}

function renderPage(
  input: VisualExportInput,
  page: RenderPage,
  pageNumber: number,
  totalPages: number,
): HTMLCanvasElement {
  abortIfRequested(input.signal);
  const scale = Math.min(2, Math.max(1, globalThis.devicePixelRatio || 1));
  const canvas = document.createElement("canvas");
  canvas.width = PAGE_WIDTH * scale;
  canvas.height = PAGE_HEIGHT * scale;
  const context = canvas.getContext("2d");
  if (!context) throw new Error("This browser cannot create the report image.");
  context.scale(scale, scale);
  context.textBaseline = "middle";
  context.fillStyle = "#ffffff";
  context.fillRect(0, 0, PAGE_WIDTH, PAGE_HEIGHT);
  context.fillStyle = "#0f172a";
  context.font = "700 28px Arial, sans-serif";
  context.fillText("SQR Billing Principal V7", PAGE_MARGIN, 36);
  context.font = "700 18px Arial, sans-serif";
  context.fillText(input.dataset.overview.target.name, PAGE_MARGIN, 72);
  context.font = "15px Arial, sans-serif";
  context.fillStyle = "#475569";
  context.fillText(
    `${page.section.title}${page.sectionPages > 1 ? ` (${page.sectionPage}/${page.sectionPages})` : ""}`,
    PAGE_MARGIN,
    108,
  );
  context.textAlign = "right";
  context.fillText(`As of ${input.dataset.overview.asOf} · revision ${input.dataset.overview.revision.revisionNumber}`, PAGE_WIDTH - PAGE_MARGIN, 36);
  context.textAlign = "left";

  const tableWidth = PAGE_WIDTH - PAGE_MARGIN * 2;
  const columnWidth = tableWidth / Math.max(1, page.section.headers.length);
  const headerLines = prepareRow(context, page.section.headers, columnWidth, HEADER_FONT);
  const headerHeight = Math.max(
    MIN_ROW_HEIGHT,
    Math.max(...headerLines.map((lines) => lines.length)) * CELL_LINE_HEIGHT + CELL_PADDING * 2,
  );
  let y = TABLE_TOP;

  const drawRow = (cells: string[][], height: number, fill: string, font: string) => {
    context.fillStyle = fill;
    context.fillRect(PAGE_MARGIN, y, tableWidth, height);
    context.strokeStyle = "#cbd5e1";
    context.strokeRect(PAGE_MARGIN, y, tableWidth, height);
    cells.forEach((lines, columnIndex) => {
      const x = PAGE_MARGIN + columnIndex * columnWidth;
      if (columnIndex > 0) {
        context.beginPath();
        context.moveTo(x, y);
        context.lineTo(x, y + height);
        context.stroke();
      }
      drawLines(context, lines, x, y, height, font);
    });
    y += height;
  };

  drawRow(headerLines, headerHeight, "#e2e8f0", HEADER_FONT);
  page.rows.forEach((row, index) => drawRow(
    row.cells,
    row.height,
    index % 2 === 0 ? "#ffffff" : "#f8fafc",
    CELL_FONT,
  ));

  context.font = "13px Arial, sans-serif";
  context.fillStyle = "#64748b";
  context.fillText(`Generated ${input.dataset.generatedAt}`, PAGE_MARGIN, PAGE_HEIGHT - 24);
  context.textAlign = "right";
  context.fillText(`Page ${pageNumber} of ${totalPages}`, PAGE_WIDTH - PAGE_MARGIN, PAGE_HEIGHT - 24);
  return canvas;
}

function canvasToPngBlob(canvas: HTMLCanvasElement): Promise<Blob> {
  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) resolve(blob);
      else reject(new Error("The browser could not encode the report image."));
    }, "image/png");
  });
}

function downloadBlob(blob: Blob, filename: string) {
  const objectUrl = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  try {
    anchor.href = objectUrl;
    anchor.download = filename;
    document.body.appendChild(anchor);
    anchor.click();
  } finally {
    anchor.remove();
    URL.revokeObjectURL(objectUrl);
  }
}

export async function exportBillingPrincipalVisualReport(
  kind: BillingPrincipalVisualExportKind,
  input: VisualExportInput,
): Promise<void> {
  const pages = buildRenderPages(input);
  const baseFilename = `billing-principal-v7-${input.dataset.overview.asOf}`;
  if (kind === "png") {
    for (let index = 0; index < pages.length; index += 1) {
      abortIfRequested(input.signal);
      const canvas = renderPage(input, pages[index]!, index + 1, pages.length);
      try {
        const blob = await canvasToPngBlob(canvas);
        abortIfRequested(input.signal);
        const suffix = pages.length === 1
          ? ""
          : `-part-${String(index + 1).padStart(3, "0")}-of-${String(pages.length).padStart(3, "0")}`;
        downloadBlob(blob, `${baseFilename}${suffix}.png`);
      } finally {
        canvas.width = 1;
        canvas.height = 1;
      }
    }
    return;
  }

  const { default: jsPDF } = await import("jspdf");
  abortIfRequested(input.signal);
  const pdf = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4", compress: true });
  const margin = 3;
  const width = pdf.internal.pageSize.getWidth() - margin * 2;
  const height = pdf.internal.pageSize.getHeight() - margin * 2;
  for (let index = 0; index < pages.length; index += 1) {
    abortIfRequested(input.signal);
    if (index > 0) pdf.addPage("a4", "landscape");
    const canvas = renderPage(input, pages[index]!, index + 1, pages.length);
    try {
      pdf.addImage(canvas, "PNG", margin, margin, width, height, undefined, "FAST");
    } finally {
      canvas.width = 1;
      canvas.height = 1;
    }
  }
  abortIfRequested(input.signal);
  pdf.save(`${baseFilename}.pdf`);
}
