import type { BillingPrincipalVisualExportDataset } from "@/lib/api/collection-billing-principal";

const systemRow = {
  aging: "D3" as const,
  totalOsp: "10000.00",
  targetPercentage: "50.0000",
  targetOsp: "5000.00",
  resultPercentage: "80.0000",
  ospClosed: "8000.00",
  closedAccountCount: 1,
};

export function createBillingPrincipalVisualExportFixture(): BillingPrincipalVisualExportDataset {
  const target = {
    id: "target-internal-id",
    name: "September governed target",
    description: "Target export fixture",
    status: "ACTIVE" as const,
    version: 1,
    activeRevision: {
      id: "revision-internal-id",
      revisionNumber: 1,
      from: "2026-09-01",
      to: "2026-09-30",
      trackingStartDate: "2026-09-01",
      trackingEndDate: "2026-09-30",
      sourceImportIds: ["source-internal-id"],
      sourceSnapshots: [{
        sourceImportId: "source-internal-id",
        name: "Saved masterlisting",
        filename: "masterlisting.xlsb",
      }],
      nicknameScope: ["TEAM A"],
      agingScope: ["D3" as const],
      createdAt: "2026-09-01T00:00:00.000Z",
    },
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  };
  const clientRow = {
    aging: "D3" as const,
    resultPercentage: "75.0000",
    ospClosed: "7500.00",
    note: "Client checkpoint",
    reference: "CLIENT-REF-1",
    effectiveDate: "2026-09-20",
    version: 1,
  };
  const reconciliation = {
    id: "reconciliation-internal-id",
    version: 2,
    status: "ACTIVE" as const,
    sourceImportId: "source-internal-id",
    sourceRecordId: "source-record-internal-id",
    sourceName: "Saved masterlisting",
    sourceFilename: "masterlisting.xlsb",
    maskedAccountNumber: "•••• 4321",
    cardNumberLast4: "9876",
    maskedCustomerName: "A•••• B•••",
    aging: "D3" as const,
    callingDate: "2026-09-01",
    totalDue: "1000.00",
    billingPrincipalOsp: "8000.00",
    systemEligibleCumulative: "700.00",
    rawSystemClassification: "CP" as const,
    manualPriorAmount: "300.00",
    asOfDate: "2026-09-20",
    actualPaymentDate: "2026-09-05",
    reconciledCumulative: "1000.00",
    reconciledRemaining: "0.00",
    reconciledStatus: "RECONCILED_CLOSED" as const,
    reconciledClosedEffectiveDate: "2026-09-10",
    reason: "PRIOR_PAYMENT_NOT_IN_SYSTEM" as const,
    note: "Verified missing prior payment",
    reference: "EVIDENCE-REF-1",
    createdBy: "superuser",
    createdAt: "2026-09-20T01:00:00.000Z",
    updatedBy: "superuser",
    updatedAt: "2026-09-20T02:00:00.000Z",
  };

  return {
    ok: true,
    generatedAt: "2026-09-20T03:00:00.000Z",
    generatedBy: "superuser",
    filters: {
      asOf: "2026-09-20",
      from: "2026-09-01",
      to: "2026-09-20",
      date: "2026-09-10",
      aging: "D3",
    },
    overview: {
      target,
      revision: target.activeRevision,
      asOf: "2026-09-20",
      systemResult: {
        rows: [systemRow],
        all: { ...systemRow, aging: "ALL" as const },
      },
      clientResult: {
        rows: [clientRow],
        all: { ...clientRow, aging: "ALL" as const },
      },
      manualReconciliation: {
        rows: [{ aging: "D3", ospClosed: "8000.00", closedAccountCount: 1 }],
        all: { aging: "ALL", ospClosed: "8000.00", closedAccountCount: 1 },
      },
      reconciledResult: {
        rows: [{
          ...systemRow,
          systemOspClosed: "0.00",
          manualReconciledOsp: "8000.00",
          reconciledOspClosed: "8000.00",
          reconciledResultPercentage: "80.0000",
        }],
        all: {
          ...systemRow,
          aging: "ALL",
          systemOspClosed: "0.00",
          manualReconciledOsp: "8000.00",
          reconciledOspClosed: "8000.00",
          reconciledResultPercentage: "80.0000",
        },
      },
      comparison: {
        rows: [{
          aging: "D3",
          systemResultPercentage: "0.0000",
          reconciledResultPercentage: "80.0000",
          clientResultPercentage: "75.0000",
          systemOspClosed: "0.00",
          manualReconciledOsp: "8000.00",
          reconciledOspClosed: "8000.00",
          clientOspClosed: "7500.00",
          systemVsClientResultPercentagePointDifference: "-75.0000",
          reconciledVsClientResultPercentagePointDifference: "5.0000",
          systemVsClientOspDifference: "-7500.00",
          reconciledVsClientOspDifference: "500.00",
        }],
      },
    },
    reconciliations: [reconciliation],
    reconciliationTotal: 1,
    calendar: [{
      date: "2026-09-10",
      aging: "ALL",
      totalOsp: "10000.00",
      targetOsp: "3300.00",
      systemOspClosedToday: "0.00",
      manualReconciliationOspClosedToday: "8000.00",
      reconciledOspClosedToday: "8000.00",
      systemCumulativeOspClosed: "0.00",
      manualReconciliationCumulativeOsp: "8000.00",
      reconciledCumulativeOspClosed: "8000.00",
      systemResultPercentage: "0.0000",
      reconciledResultPercentage: "80.0000",
      clientResultPercentage: null,
      systemPreviousResultPercentage: "0.0000",
      reconciledPreviousResultPercentage: "0.0000",
      systemDailyMovementPercentagePoints: "0.0000",
      reconciledDailyMovementPercentagePoints: "80.0000",
      systemAchievementVsTargetPercentage: "0.0000",
      reconciledAchievementVsTargetPercentage: "242.4242",
      systemDailyAccounts: 0,
      manualDailyAccounts: 1,
      reconciledDailyAccounts: 1,
    }],
    drilldown: [{
      contributionSource: "MANUAL_RECONCILIATION",
      maskedAccountNumber: "•••• 4321",
      cardNumberLast4: "9876",
      maskedCustomerName: "A•••• B•••",
      sourceName: "September Masterlisting",
      sourceFilename: "npl-september.xlsb",
      callingDate: "2026-09-01",
      aging: "D3",
      totalDue: "1000.00",
      systemEligibleCumulative: "700.00",
      systemClosureCollectionAmount: null,
      systemClosureStaffNickname: null,
      manualPriorAmount: "300.00",
      reconciledCumulative: "1000.00",
      billingPrincipalOsp: "8000.00",
      effectiveClosedDate: "2026-09-10",
      reason: "PRIOR_PAYMENT_NOT_IN_SYSTEM",
      reference: "EVIDENCE-REF-1",
      reconciliationCreatedBy: "superuser",
      reconciliationCreatedAt: "2026-09-10T01:00:00.000Z",
      reconciliationUpdatedBy: "superuser",
      reconciliationUpdatedAt: "2026-09-10T01:00:00.000Z",
    }],
    drilldownTotal: 1,
  };
}
