import {
  type RoleTabSetting,
  ROLE_TAB_SETTINGS,
  roleTabSettingKey,
} from "../config/system-settings";
import type { SettingsCategorySeedItem, SettingsSeedItem } from "./settings-bootstrap-shared";

export const SETTINGS_CATEGORIES: SettingsCategorySeedItem[] = [
  { name: "General", description: "Global platform behavior and identity settings." },
  { name: "Security", description: "Authentication, session, and security policy controls." },
  { name: "AI & Search", description: "AI assistant and search tuning configuration." },
  { name: "Data Management", description: "Data processing, viewer, and indexing limits." },
  { name: "Backup & Restore", description: "Backup lifecycle and recovery controls." },
  { name: "Roles & Permissions", description: "Role behavior and privilege defaults." },
  { name: "System Monitoring", description: "WebSocket and runtime diagnostics settings." },
];

const BASE_SETTINGS_SEED: SettingsSeedItem[] = [
  {
    categoryName: "General",
    key: "system_name",
    label: "System Name",
    description: "Display name shown in application header.",
    type: "text",
    value: "SQR System",
    defaultValue: "SQR System",
    isCritical: false,
  },
  {
    categoryName: "General",
    key: "session_timeout_minutes",
    label: "Session Timeout (Minutes)",
    description: "Default idle timeout duration for authenticated sessions.",
    type: "number",
    value: "30",
    defaultValue: "30",
    isCritical: true,
  },
  {
    categoryName: "Security",
    key: "jwt_expiry_hours",
    label: "JWT Expiry (Hours)",
    description: "Token validity period used during login.",
    type: "number",
    value: "24",
    defaultValue: "24",
    isCritical: true,
  },
  {
    categoryName: "Security",
    key: "enforce_superuser_single_session",
    label: "Enforce Single Superuser Session",
    description: "Force single active session for superuser accounts.",
    type: "boolean",
    value: "true",
    defaultValue: "true",
    isCritical: false,
  },
  {
    categoryName: "AI & Search",
    key: "ai_enabled",
    label: "Enable AI Assistant",
    description: "Controls AI endpoints and chat behavior.",
    type: "boolean",
    value: "true",
    defaultValue: "true",
    isCritical: false,
  },
  {
    categoryName: "AI & Search",
    key: "semantic_search_enabled",
    label: "Enable Semantic Search",
    description: "Allow pgvector semantic retrieval for AI workflows.",
    type: "boolean",
    value: "true",
    defaultValue: "true",
    isCritical: false,
  },
  {
    categoryName: "AI & Search",
    key: "ai_timeout_ms",
    label: "AI Timeout (ms)",
    description: "Server timeout for AI requests before fallback response.",
    type: "number",
    value: "6000",
    defaultValue: "6000",
    isCritical: false,
  },
  {
    categoryName: "Data Management",
    key: "search_result_limit",
    label: "Search Result Limit",
    description: "Maximum records returned in search APIs.",
    type: "number",
    value: "200",
    defaultValue: "200",
    isCritical: false,
  },
  {
    categoryName: "Data Management",
    key: "viewer_rows_per_page",
    label: "Viewer Rows Per Page",
    description: "Default row count per viewer page.",
    type: "number",
    value: "100",
    defaultValue: "100",
    isCritical: false,
  },
  {
    categoryName: "Backup & Restore",
    key: "backup_retention_days",
    label: "Backup Retention (Days)",
    description: "Retention target for automated backup lifecycle policies.",
    type: "number",
    value: "30",
    defaultValue: "30",
    isCritical: false,
  },
  {
    categoryName: "Backup & Restore",
    key: "backup_auto_cleanup_enabled",
    label: "Enable Backup Auto Cleanup",
    description: "Automatically remove backups older than retention policy.",
    type: "boolean",
    value: "false",
    defaultValue: "false",
    isCritical: false,
  },
  {
    categoryName: "Roles & Permissions",
    key: "admin_can_edit_maintenance_message",
    label: "Admin Can Edit Maintenance Message",
    description: "Allow admin role to edit maintenance message and window only.",
    type: "boolean",
    value: "true",
    defaultValue: "true",
    isCritical: false,
  },
  {
    categoryName: "Roles & Permissions",
    key: "canViewSystemPerformance",
    label: "View System Performance",
    description: "Allow admin role to view System Performance in System Monitor.",
    type: "boolean",
    value: "false",
    defaultValue: "false",
    isCritical: false,
  },
  {
    categoryName: "System Monitoring",
    key: "ws_idle_minutes",
    label: "WebSocket Idle Timeout (Minutes)",
    description: "Idle timeout before websocket session termination.",
    type: "number",
    value: "3",
    defaultValue: "3",
    isCritical: false,
  },
  {
    categoryName: "System Monitoring",
    key: "debug_logs_enabled",
    label: "Enable Debug Logs",
    description: "Enable verbose API debug logging.",
    type: "boolean",
    value: "false",
    defaultValue: "false",
    isCritical: false,
  },
  {
    categoryName: "System Monitoring",
    key: "maintenance_mode",
    label: "Maintenance Mode",
    description: "Master switch for maintenance mode activation.",
    type: "boolean",
    value: "false",
    defaultValue: "false",
    isCritical: true,
  },
  {
    categoryName: "System Monitoring",
    key: "maintenance_message",
    label: "Maintenance Message",
    description: "Message shown to end users while maintenance is active.",
    type: "text",
    value: "Sistem sedang diselenggara. Sila cuba semula sebentar lagi.",
    defaultValue: "Sistem sedang diselenggara. Sila cuba semula sebentar lagi.",
    isCritical: false,
  },
  {
    categoryName: "System Monitoring",
    key: "maintenance_type",
    label: "Maintenance Type",
    description: "Soft mode limits selected modules. Hard mode blocks all protected routes.",
    type: "select",
    value: "soft",
    defaultValue: "soft",
    isCritical: true,
  },
  {
    categoryName: "System Monitoring",
    key: "maintenance_start_time",
    label: "Maintenance Start Time",
    description: "Optional ISO timestamp to schedule maintenance start.",
    type: "timestamp",
    value: "",
    defaultValue: "",
    isCritical: false,
  },
  {
    categoryName: "System Monitoring",
    key: "maintenance_end_time",
    label: "Maintenance End Time",
    description: "Optional ISO timestamp to auto-end maintenance.",
    type: "timestamp",
    value: "",
    defaultValue: "",
    isCritical: false,
  },
];

export const ADMIN_EDITABLE_SETTING_KEYS = new Set([
  "system_name",
  "ai_enabled",
  "semantic_search_enabled",
  "ai_timeout_ms",
  "search_result_limit",
  "viewer_rows_per_page",
  "maintenance_message",
  "maintenance_start_time",
  "maintenance_end_time",
]);

export const MAINTENANCE_TYPE_OPTIONS = [
  { value: "soft", label: "Soft Maintenance" },
  { value: "hard", label: "Hard Maintenance" },
] as const;

export function buildSettingsSeedItems(): SettingsSeedItem[] {
  const settingsSeed = [...BASE_SETTINGS_SEED];

  for (const [role, tabSettings] of Object.entries(ROLE_TAB_SETTINGS) as Array<["admin" | "user", RoleTabSetting[]]>) {
    for (const tabSetting of tabSettings) {
      settingsSeed.push({
        categoryName: "Roles & Permissions",
        key: roleTabSettingKey(role, tabSetting.suffix),
        label: tabSetting.label,
        description: tabSetting.description,
        type: "boolean",
        value: tabSetting.defaultEnabled ? "true" : "false",
        defaultValue: tabSetting.defaultEnabled ? "true" : "false",
        isCritical: false,
      });
    }
  }

  return settingsSeed;
}
