import { lazyWithPreload } from "@/lib/lazy-with-preload";

export const LandingPage = lazyWithPreload(() => import("@/pages/Landing"));
export const LoginPage = lazyWithPreload(() => import("@/pages/Login"));
export const ForgotPasswordPage = lazyWithPreload(() => import("@/pages/ForgotPassword"));
export const ActivateAccountPage = lazyWithPreload(() => import("@/pages/ActivateAccount"));
export const ResetPasswordPage = lazyWithPreload(() => import("@/pages/ResetPassword"));
export const ChangePasswordPage = lazyWithPreload(() => import("@/pages/ChangePassword"));
export const SingleTabBlockedPage = lazyWithPreload(() => import("@/pages/SingleTabBlocked"));
export const HomePage = lazyWithPreload(() => import("@/pages/Home"));
export const ImportPage = lazyWithPreload(() => import("@/pages/Import"));
export const SavedPage = lazyWithPreload(() => import("@/pages/Saved"));
export const ViewerPage = lazyWithPreload(() => import("@/pages/Viewer"));
export const GeneralSearchPage = lazyWithPreload(() => import("@/pages/GeneralSearch"));
export const BackupRestorePage = lazyWithPreload(() => import("@/pages/BackupRestore"));
export const AIPage = lazyWithPreload(() => import("@/pages/AI"));
export const BannedPage = lazyWithPreload(() => import("@/pages/Banned"));
export const SettingsRoutePage = lazyWithPreload(() => import("@/pages/Settings"));
export const MaintenanceRoutePage = lazyWithPreload(() => import("@/pages/Maintenance"));
export const SystemMonitorLayoutPage = lazyWithPreload(() => import("@/pages/SystemMonitorLayout"));
export const CollectionReportPage = lazyWithPreload(() => import("@/pages/CollectionReport"));
export const ForbiddenPage = lazyWithPreload(() => import("@/pages/Forbidden"));
export const NotFoundPage = lazyWithPreload(() => import("@/pages/NotFound"));
