import { PostgresOperationsStorage } from "./storage/postgres/postgres-operations-storage";
import type { IStorage } from "./storage-postgres-types";

export type {
  AccountActivationTokenSummary,
  CollectionAdminGroup,
  CollectionAdminUser,
  CollectionDailyCalendarAuditEntry,
  CollectionDailyCalendarDay,
  CollectionDailyPaidCustomer,
  CollectionDailyTarget,
  CollectionDailyUser,
  CollectionMonthlyComparisonAggregate,
  CollectionMonthlySummary,
  CollectionNicknameAggregate,
  CollectionNicknameDailyAggregate,
  CollectionNicknameAuthProfile,
  CollectionNicknameSession,
  CollectionRecord,
  CollectionManualSettlement,
  CollectionManualSettlementReason,
  CollectionManualSettlementStatus,
  CollectionManualSettlementValidity,
  CollectionEffectiveSettlementSource,
  CollectionRecordAggregateFilters,
  CollectionRecordAggregate,
  CollectionRecordListFilters,
  CollectionRecordReceipt,
  CollectionReceiptDuplicateSummary,
  CollectionReceiptExtractionStatus,
  CollectionReceiptValidationStatus,
  CollectionRollupFreshnessSnapshot,
  CollectionStaffNickname,
  CollectionLegacyBackfillStats,
  CollectionSourceConfig,
  ConfigureCollectionSourceInput,
  CollectionSourceMatchResult,
  CollectionBillingPrincipalReport,
  CollectionOspTargetInput,
  CollectionOspSavedTargetView,
  CollectionOspManualReasonCode,
  CollectionOspManualReconciliationView,
  CollectionOspReconciliationCandidateView,
  CollectionOspReconciliationHistoryView,
  CollectionOspClientResultView,
  CollectionOspCalendarDayView,
  CollectionOspDrilldownItemView,
  CollectionOspPagination,
  CreateCollectionRecordInput,
  CreateCollectionRecordReceiptInput,
  CreateCollectionStaffNicknameInput,
  DeleteCollectionRecordOptions,
  IStorage,
  ManagedUserAccount,
  MutationIdempotencyAcquireInput,
  MutationIdempotencyAcquireResult,
  MutationIdempotencyCompleteInput,
  PasswordResetTokenSummary,
  PendingPasswordResetRequestSummary,
  UpdateCollectionRecordReceiptInput,
  UpdateCollectionRecordInput,
  UpdateCollectionRecordOptions,
  UpdateCollectionStaffNicknameInput,
} from "./storage-postgres-types";

export class PostgresStorage extends PostgresOperationsStorage implements IStorage {}

export const storage: IStorage = new PostgresStorage();
