export const auditDetailLabelMap: Record<string, string> = {
  action: "Tindakan",
  activeReceiptCount: "Bilangan resit aktif",
  activeReceiptSource: "Sumber resit aktif",
  actor: "Dilakukan oleh",
  actor_user_id: "ID pengguna pelaksana",
  addedCount: "Bilangan ditambah",
  amount: "Jumlah",
  batch: "Batch",
  beforeCount: "Bilangan sebelum",
  beforeSource: "Sumber sebelum",
  backupId: "ID backup",
  browser: "Browser",
  changedField: "Medan diubah",
  clearedLegacyFallback: "Fallback resit lama dikosongkan",
  closed_session_ids: "Sesi ditutup",
  collectionStaffNickname: "Nickname collection",
  customerName: "Nama pelanggan",
  date: "Tarikh",
  deleted_role: "Peranan dipadam",
  deleted_status: "Status dipadam",
  delivery: "Kaedah penghantaran",
  delivery_mode: "Mode penghantaran",
  duplicates: "Resit duplicate",
  durationMs: "Tempoh proses",
  email_changed: "Email diubah",
  enabled_at: "Masa diaktifkan",
  event: "Event",
  event_type: "Jenis event",
  expires_at: "Tamat tempoh",
  failed_login_attempts: "Cubaan login gagal",
  failure_reason: "Sebab gagal",
  from: "Tarikh mula",
  full_name_changed: "Nama penuh diubah",
  inserted: "Berjaya dimasukkan",
  integrityVerified: "Integriti disahkan",
  ip: "IP",
  latKey: "Medan latitude",
  leaveType: "Jenis cuti",
  lngKey: "Medan longitude",
  lock_cleared: "Lock akaun dibersihkan",
  locked: "Akaun dikunci",
  locked_by_system: "Dikunci sistem",
  locked_reason: "Sebab dikunci",
  mail_error_code: "Kod ralat email",
  must_change_password: "Wajib tukar password",
  nameKey: "Medan nama",
  next_role: "Peranan selepas",
  next_status: "Status selepas",
  nickname: "Nickname",
  nicknameCount: "Bilangan nickname",
  note: "Nota",
  page: "Halaman",
  pageSize: "Rekod setiap halaman",
  passwordResetBySuperuser: "Password reset oleh superuser",
  payloadBytes: "Saiz payload",
  paymentDate: "Tarikh bayaran",
  pc_name: "Nama PC",
  previous_role: "Peranan sebelum",
  previous_status: "Status sebelum",
  receiptCount: "Bilangan resit",
  recipient_email: "Email penerima",
  recordCount: "Rekod dipaparkan",
  recordId: "ID rekod",
  removedArchivedCount: "Arkib resit dibuang",
  removedCount: "Bilangan dibuang",
  removedLegacyFallback: "Fallback resit lama dibuang",
  removedReceiptIds: "ID resit dibuang",
  replaced: "Resit diganti",
  request_id: "Request ID",
  resent: "Dihantar semula",
  reset_type: "Jenis reset",
  retry_count: "Bilangan cubaan",
  role: "Peranan",
  searchPresent: "Carian digunakan",
  skipped: "Dilangkau",
  status: "Status",
  targetUser: "Pengguna sasaran",
  target_user_id: "ID pengguna sasaran",
  timestamp: "Masa",
  to: "Tarikh akhir",
  totalInserted: "Jumlah dimasukkan",
  totalProcessed: "Jumlah diproses",
  totalReactivated: "Jumlah diaktifkan semula",
  totalRecords: "Jumlah rekod",
  totalSkipped: "Jumlah dilangkau",
  user_agent: "User agent",
  user_id: "ID pengguna",
  username: "Username",
  username_changed: "Username diubah",
  warningCount: "Jumlah amaran",
  was_banned: "Pernah diban",
};

export const auditDetailGroupLabelMap: Record<string, string> = {
  after: "Selepas",
  before: "Sebelum",
  changes: "Perubahan",
  deleted: "Dipadam",
  device: "Peranti",
  metadata: "",
  receipts: "Resit",
  snapshot: "Ringkasan rekod",
  usedKeys: "Medan digunakan",
};

export const priorityDetailKeys = [
  "event",
  "event_type",
  "role",
  "actor",
  "username",
  "user_id",
  "target_user_id",
  "recordId",
  "backupId",
  "recordCount",
  "totalRecords",
  "totalProcessed",
  "totalInserted",
  "totalSkipped",
  "totalReactivated",
  "page",
  "pageSize",
  "from",
  "to",
  "date",
  "paymentDate",
  "nickname",
  "collectionStaffNickname",
  "nicknameCount",
  "searchPresent",
  "status",
  "leaveType",
  "amount",
  "receiptCount",
  "activeReceiptCount",
  "note",
  "previous_role",
  "next_role",
  "previous_status",
  "next_status",
  "expires_at",
  "lock_cleared",
  "durationMs",
  "integrityVerified",
];
