import { memo } from "react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { InfoHint } from "@/components/monitor/InfoHint";
import { useIsMobile } from "@/hooks/use-mobile";
import type { MonitorSnapshot } from "@/hooks/useSystemMetrics";

type MonitorOverviewStatsGridProps = {
  snapshot: MonitorSnapshot;
  rollupFreshnessSummary: string;
  rollupFreshnessAgeLabel: string;
};

function MonitorOverviewStatsGridImpl({
  snapshot,
  rollupFreshnessSummary,
  rollupFreshnessAgeLabel,
}: MonitorOverviewStatsGridProps) {
  const isMobile = useIsMobile();

  return (
    <div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-5">
      <Card className="border-border/60 bg-background/45">
        <CardContent className="p-4">
          <div className="flex items-center gap-2">
            <p className="text-xs uppercase tracking-wide text-muted-foreground">System Mode</p>
            <InfoHint text="Operational state: NORMAL, DEGRADED, or PROTECTION." />
          </div>
          <p className="mt-2 text-2xl font-semibold">{snapshot.mode}</p>
        </CardContent>
      </Card>
      <Card className="border-border/60 bg-background/45">
        <CardContent className="p-4">
          <div className="flex items-center gap-2">
            <p className="text-xs uppercase tracking-wide text-muted-foreground">Bottleneck Type</p>
            <InfoHint text="Primary pressure source currently limiting performance." />
          </div>
          <p className="mt-2 text-2xl font-semibold">{snapshot.bottleneckType}</p>
        </CardContent>
      </Card>
      <Card className="border-border/60 bg-background/45">
        <CardContent className="p-4">
          <div className="flex items-center gap-2">
            <p className="text-xs uppercase tracking-wide text-muted-foreground">Worker Count</p>
            <InfoHint text="Active workers versus configured worker capacity." />
          </div>
          <p className="mt-2 text-2xl font-semibold">
            {snapshot.workerCount} / {snapshot.maxWorkers}
          </p>
        </CardContent>
      </Card>
      <Card className="border-border/60 bg-background/45">
        <CardContent className="p-4">
          <div className="flex items-center gap-2">
            <p className="text-xs uppercase tracking-wide text-muted-foreground">Rollup Queue</p>
            <InfoHint text="Pending background refresh slices keeping collection report rollups up to date." />
          </div>
          <p className="mt-2 text-2xl font-semibold">{snapshot.rollupRefreshPendingCount}</p>
          <p className="mt-1 text-xs text-muted-foreground">{rollupFreshnessSummary}</p>
          {isMobile ? (
            <div className="mt-2 flex flex-wrap gap-2">
              <Badge variant="secondary" className="rounded-full px-2.5 py-0.5 text-[10px]">
                {snapshot.rollupRefreshRunningCount} running
              </Badge>
              <Badge variant="outline" className="rounded-full px-2.5 py-0.5 text-[10px]">
                {snapshot.rollupRefreshRetryCount} retry
              </Badge>
              <Badge variant="outline" className="rounded-full px-2.5 py-0.5 text-[10px]">
                Oldest {rollupFreshnessAgeLabel}
              </Badge>
            </div>
          ) : (
            <p className="mt-1 text-xs text-muted-foreground">
              {snapshot.rollupRefreshRunningCount} running, {snapshot.rollupRefreshRetryCount} retry, oldest {rollupFreshnessAgeLabel}
            </p>
          )}
        </CardContent>
      </Card>
      <Card className="border-border/60 bg-background/45">
        <CardContent className="p-4">
          <div className="flex items-center gap-2">
            <p className="text-xs uppercase tracking-wide text-muted-foreground">Active Alert Count</p>
            <InfoHint text="Number of currently open alerts generated by monitor rules." />
          </div>
          <p className="mt-2 text-2xl font-semibold">{snapshot.activeAlertCount}</p>
        </CardContent>
      </Card>
    </div>
  );
}

export const MonitorOverviewStatsGrid = memo(MonitorOverviewStatsGridImpl);
