import {
  createCollectionAdminGroupRepository,
  deleteCollectionAdminGroupRepository,
  getCollectionAdminAssignedNicknameIdsRepository,
  getCollectionAdminGroupByIdRepository,
  getCollectionAdminGroupsRepository,
  getCollectionAdminGroupVisibleNicknameValuesByLeaderRepository,
  getCollectionAdminUserByIdRepository,
  getCollectionAdminUsersRepository,
  getCollectionAdminVisibleNicknamesRepository,
  setCollectionAdminAssignedNicknameIdsRepository,
  updateCollectionAdminGroupRepository,
} from "./collection-repository-admin-operations";
import {
  getCollectionDailyTargetRepository,
  listCollectionDailyCalendarRepository,
  listCollectionDailyPaidCustomersRepository,
  listCollectionDailyUsersRepository,
  upsertCollectionDailyCalendarDaysRepository,
  upsertCollectionDailyTargetRepository,
} from "./collection-repository-daily-operations";
import {
  clearCollectionNicknameSessionByActivityRepository,
  getCollectionAdminNicknameAccessContextByActivityRepository,
  createCollectionStaffNicknameRepository,
  deleteCollectionStaffNicknameRepository,
  getCollectionNicknameAuthProfileByNameRepository,
  getCollectionNicknameSessionByActivityRepository,
  getCollectionStaffNicknameByIdRepository,
  getCollectionStaffNicknameByNameRepository,
  getCollectionStaffNicknamesRepository,
  isCollectionStaffNicknameActiveRepository,
  setCollectionNicknamePasswordRepository,
  setCollectionNicknameSessionRepository,
  updateCollectionStaffNicknameRepository,
} from "./collection-repository-nickname-operations";
import {
  createCollectionRecordRepository,
  deleteCollectionRecordRepository,
  getCollectionMonthlySummaryRepository,
  getCollectionRecordByIdRepository,
  getCollectionRecordDailyRollupFreshnessRepository,
  listCollectionRecordsRepository,
  purgeCollectionRecordsOlderThanRepository,
  summarizeCollectionRecordsByNicknameAndPaymentDateRepository,
  summarizeCollectionRecordsByNicknameRepository,
  summarizeCollectionRecordsOlderThanRepository,
  summarizeCollectionRecordsRepository,
  updateCollectionRecordRepository,
} from "./collection-repository-record-operations";
import {
  createCollectionRecordReceiptsRepository,
  deleteAllCollectionRecordReceiptsRepository,
  deleteCollectionRecordReceiptsRepository,
  findCollectionReceiptDuplicateSummariesRepository,
  getCollectionRecordReceiptByIdRepository,
  listCollectionRecordReceiptsRepository,
  syncCollectionRecordReceiptValidationRepository,
  updateCollectionRecordReceiptsRepository,
} from "./collection-repository-receipt-operations";

export class CollectionRepository {
  readonly clearCollectionNicknameSessionByActivity = clearCollectionNicknameSessionByActivityRepository;
  readonly getCollectionAdminNicknameAccessContextByActivity =
    getCollectionAdminNicknameAccessContextByActivityRepository;
  readonly createCollectionAdminGroup = createCollectionAdminGroupRepository;
  readonly createCollectionRecord = createCollectionRecordRepository;
  readonly createCollectionRecordReceipts = createCollectionRecordReceiptsRepository;
  readonly createCollectionStaffNickname = createCollectionStaffNicknameRepository;
  readonly deleteAllCollectionRecordReceipts = deleteAllCollectionRecordReceiptsRepository;
  readonly deleteCollectionAdminGroup = deleteCollectionAdminGroupRepository;
  readonly deleteCollectionRecord = deleteCollectionRecordRepository;
  readonly deleteCollectionRecordReceipts = deleteCollectionRecordReceiptsRepository;
  readonly deleteCollectionStaffNickname = deleteCollectionStaffNicknameRepository;
  readonly findCollectionReceiptDuplicateSummaries = findCollectionReceiptDuplicateSummariesRepository;
  readonly getCollectionAdminAssignedNicknameIds = getCollectionAdminAssignedNicknameIdsRepository;
  readonly getCollectionAdminGroupById = getCollectionAdminGroupByIdRepository;
  readonly getCollectionAdminGroups = getCollectionAdminGroupsRepository;
  readonly getCollectionAdminGroupVisibleNicknameValuesByLeader =
    getCollectionAdminGroupVisibleNicknameValuesByLeaderRepository;
  readonly getCollectionAdminUserById = getCollectionAdminUserByIdRepository;
  readonly getCollectionAdminUsers = getCollectionAdminUsersRepository;
  readonly getCollectionAdminVisibleNicknames = getCollectionAdminVisibleNicknamesRepository;
  readonly getCollectionDailyTarget = getCollectionDailyTargetRepository;
  readonly getCollectionMonthlySummary = getCollectionMonthlySummaryRepository;
  readonly getCollectionNicknameAuthProfileByName = getCollectionNicknameAuthProfileByNameRepository;
  readonly getCollectionNicknameSessionByActivity = getCollectionNicknameSessionByActivityRepository;
  readonly getCollectionRecordById = getCollectionRecordByIdRepository;
  readonly getCollectionRecordDailyRollupFreshness = getCollectionRecordDailyRollupFreshnessRepository;
  readonly getCollectionRecordReceiptById = getCollectionRecordReceiptByIdRepository;
  readonly getCollectionStaffNicknameById = getCollectionStaffNicknameByIdRepository;
  readonly getCollectionStaffNicknameByName = getCollectionStaffNicknameByNameRepository;
  readonly getCollectionStaffNicknames = getCollectionStaffNicknamesRepository;
  readonly isCollectionStaffNicknameActive = isCollectionStaffNicknameActiveRepository;
  readonly listCollectionDailyCalendar = listCollectionDailyCalendarRepository;
  readonly listCollectionDailyPaidCustomers = listCollectionDailyPaidCustomersRepository;
  readonly listCollectionDailyUsers = listCollectionDailyUsersRepository;
  readonly listCollectionRecordReceipts = listCollectionRecordReceiptsRepository;
  readonly listCollectionRecords = listCollectionRecordsRepository;
  readonly purgeCollectionRecordsOlderThan = purgeCollectionRecordsOlderThanRepository;
  readonly setCollectionAdminAssignedNicknameIds = setCollectionAdminAssignedNicknameIdsRepository;
  readonly setCollectionNicknamePassword = setCollectionNicknamePasswordRepository;
  readonly setCollectionNicknameSession = setCollectionNicknameSessionRepository;
  readonly summarizeCollectionRecords = summarizeCollectionRecordsRepository;
  readonly summarizeCollectionRecordsByNickname = summarizeCollectionRecordsByNicknameRepository;
  readonly summarizeCollectionRecordsByNicknameAndPaymentDate =
    summarizeCollectionRecordsByNicknameAndPaymentDateRepository;
  readonly summarizeCollectionRecordsOlderThan = summarizeCollectionRecordsOlderThanRepository;
  readonly syncCollectionRecordReceiptValidation = syncCollectionRecordReceiptValidationRepository;
  readonly updateCollectionAdminGroup = updateCollectionAdminGroupRepository;
  readonly updateCollectionRecord = updateCollectionRecordRepository;
  readonly updateCollectionRecordReceipts = updateCollectionRecordReceiptsRepository;
  readonly updateCollectionStaffNickname = updateCollectionStaffNicknameRepository;
  readonly upsertCollectionDailyCalendarDays = upsertCollectionDailyCalendarDaysRepository;
  readonly upsertCollectionDailyTarget = upsertCollectionDailyTargetRepository;
}
