import { z } from "zod";

export const ERROR_CODES = {
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
  REQUEST_BODY_INVALID: "REQUEST_BODY_INVALID",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_IDENTIFIER: "INVALID_IDENTIFIER",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
  INVALID_TOKEN: "INVALID_TOKEN",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USERNAME_TAKEN: "USERNAME_TAKEN",
  NOT_FOUND: "NOT_FOUND",
  TOKEN_USED: "TOKEN_USED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_UNAVAILABLE: "ACCOUNT_UNAVAILABLE",
  ACCOUNT_BANNED: "ACCOUNT_BANNED",
  PASSWORD_CHANGE_REQUIRED: "PASSWORD_CHANGE_REQUIRED",
  SUPERUSER_SINGLE_SESSION_ENFORCED: "SUPERUSER_SINGLE_SESSION_ENFORCED",
  AUTH_RATE_LIMITED: "AUTH_RATE_LIMITED",
  IMPORT_UPLOAD_RATE_LIMITED: "IMPORT_UPLOAD_RATE_LIMITED",
  AUTH_RECOVERY_RATE_LIMITED: "AUTH_RECOVERY_RATE_LIMITED",
  AUTH_MUTATION_RATE_LIMITED: "AUTH_MUTATION_RATE_LIMITED",
  ADMIN_ACTION_RATE_LIMITED: "ADMIN_ACTION_RATE_LIMITED",
  SEARCH_RATE_LIMITED: "SEARCH_RATE_LIMITED",
  TWO_FACTOR_CHALLENGE_INVALID: "TWO_FACTOR_CHALLENGE_INVALID",
  TWO_FACTOR_INVALID_CODE: "TWO_FACTOR_INVALID_CODE",
  TWO_FACTOR_NOT_ENABLED: "TWO_FACTOR_NOT_ENABLED",
  TWO_FACTOR_NOT_ALLOWED: "TWO_FACTOR_NOT_ALLOWED",
  TWO_FACTOR_SECRET_INVALID: "TWO_FACTOR_SECRET_INVALID",
  TWO_FACTOR_SETUP_MISSING: "TWO_FACTOR_SETUP_MISSING",
  MAIL_PREVIEW_NOT_FOUND: "MAIL_PREVIEW_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

const sharedErrorCodeValues = Object.values(ERROR_CODES) as [ErrorCode, ...ErrorCode[]];

export const sharedErrorCodeSchema = z.enum(sharedErrorCodeValues);
