export const ERROR_CODES = {
  REQUEST_BODY_INVALID: "REQUEST_BODY_INVALID",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  AUTH_RATE_LIMITED: "AUTH_RATE_LIMITED",
  AUTH_RECOVERY_RATE_LIMITED: "AUTH_RECOVERY_RATE_LIMITED",
  AUTH_MUTATION_RATE_LIMITED: "AUTH_MUTATION_RATE_LIMITED",
  ADMIN_ACTION_RATE_LIMITED: "ADMIN_ACTION_RATE_LIMITED",
  SEARCH_RATE_LIMITED: "SEARCH_RATE_LIMITED",
  TWO_FACTOR_CHALLENGE_INVALID: "TWO_FACTOR_CHALLENGE_INVALID",
  TWO_FACTOR_INVALID_CODE: "TWO_FACTOR_INVALID_CODE",
  TWO_FACTOR_NOT_ENABLED: "TWO_FACTOR_NOT_ENABLED",
  TWO_FACTOR_SECRET_INVALID: "TWO_FACTOR_SECRET_INVALID",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
