export const SQR_TRUSTED_TYPES_POLICY_NAME = "sqr-ui"
export const DOMPURIFY_TRUSTED_TYPES_POLICY_NAME = "dompurify"

export const SQR_ALLOWED_TRUSTED_TYPES_POLICY_NAMES = [
  "default",
  SQR_TRUSTED_TYPES_POLICY_NAME,
  DOMPURIFY_TRUSTED_TYPES_POLICY_NAME,
] as const
