import assert from "node:assert/strict";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { SystemStatusView } from "../client/src/components/system-status/SystemStatusView";
import { SYSTEM_STATUS_CONTENT } from "../shared/system-status";

// Build-time React only: output has no React/runtime/dependency or external fetch.
const output = path.resolve("deploy/errors");
const check = process.argv.includes("--check");
function emit(relative: string, content: string) {
  const target = path.join(output, relative);
  if (check) { assert.equal(readFileSync(target, "utf8").replace(/\r\n/g, "\n"), content.replace(/\r\n/g, "\n"), `Rebuild static status artifact: ${relative}`); return; }
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, content, "utf8");
}
// Copy only the four existing safe-area tokens, not the application's CSS framework.
const safeAreaSource = readFileSync("client/src/styles/tokens/_safe-area.css", "utf8");
const safeAreaTokens = safeAreaSource.match(/--safe-area-inset-(?:top|right|bottom|left):[^;]+;/g);
assert.equal(safeAreaTokens?.length, 4, "Expected the four canonical safe-area tokens.");
emit("assets/status.css", `:root { ${safeAreaTokens!.join(" ")} }\n`
  + readFileSync("client/src/components/system-status/SystemStatusPage.css", "utf8")
  + "\nbody { margin: 0; }\n.sqr-status-noscript { margin: 20px; font: 1rem system-ui; }\n");
emit("assets/sqr-logo.svg", readFileSync("client/public/brand/sqr-logo-minimal.svg", "utf8"));
for (const state of ["502", "503", "504", "maintenance"] as const) {
  const body = renderToStaticMarkup(createElement(SystemStatusView, { state,
    primary: { label: "Cuba Semula", href: "/" },
    secondary: state === "maintenance" ? { label: "Kembali ke Log Masuk", href: "/login" } : undefined,
    staticRecovery: true, logoSrc: "/_sqr/errors/assets/sqr-logo.svg" }));
  emit(`${state}.html`, `<!doctype html>\n<!-- Generated by npm run build:status; edit the shared status view/copy/CSS. -->\n<html lang="ms"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="robots" content="noindex, nofollow"><meta name="referrer" content="no-referrer"><title>SQR — ${SYSTEM_STATUS_CONTENT[state].title}</title><link rel="stylesheet" href="/_sqr/errors/assets/status.css"><script defer src="/_sqr/errors/assets/status.js"></script></head><body>${body}<noscript><p class="sqr-status-noscript">Semakan automatik memerlukan JavaScript. Pautan Cuba Semula membawa anda ke halaman utama SQR tanpa menghantar semula borang.</p></noscript></body></html>\n`);
}
console.log(check ? "Static status artifacts match their shared source." : "Static status artifacts generated (no browser framework runtime).");
