import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function readSource(fileName: string) {
  return readFileSync(path.resolve(__dirname, fileName), "utf8");
}

test("navbar controls use Malay accessible labels and include username context", () => {
  const navbarSource = readSource("Navbar.tsx");
  const navbarPartsSource = readSource("NavbarParts.tsx");
  const notificationCenterSource = readSource("NavbarNotificationCenter.tsx");
  const navbarCombinedSource = `${navbarSource}\n${navbarPartsSource}`;
  const homeButtonSource = readSource("NavbarHomeButton.tsx");
  const desktopNavigationSource = readSource("NavbarDesktopNavigation.tsx");
  const userMenuSource = readSource("NavbarUserMenuContent.tsx");
  const mobileNavigationSource = readSource("NavbarMobileNavigation.tsx");
  const scrollHintSource = readSource("HorizontalScrollHint.tsx");
  const navbarStyles = readSource("Navbar.css");

  assert.match(navbarSource, /aria-label=\{translate\("common\.navbar\.mobileMenuLabel"\)\}/);
  assert.match(navbarSource, /\{translate\("common\.navbar\.mobileMenuText"\)\}/);
  assert.match(navbarSource, /<button[\s\S]*data-testid="button-open-mobile-nav"/);
  assert.doesNotMatch(navbarSource, /<div[^>]*data-testid="button-open-mobile-nav"/);
  assert.match(navbarSource, /getAriaExpandedProps\(mobileNavOpen\)/);
  assert.doesNotMatch(navbarSource, /"aria-expanded": mobileNavOpen/);
  assert.match(navbarSource, /useNotificationHistoryState\(\)/);
  assert.match(navbarSource, /variant="mobile"/);
  assert.match(navbarSource, /variant="desktop"/);
  assert.match(notificationCenterSource, /aria-label=\{triggerLabel\}/);
  assert.match(notificationCenterSource, /aria-label="Pusat notifikasi"/);
  assert.match(notificationCenterSource, /aria-label="Kosongkan sejarah notifikasi"/);
  assert.match(notificationCenterSource, /aria-label=\{`Sejarah notifikasi \$\{group\.module\}`\}/);
  assert.match(notificationCenterSource, /aria-label="Notifikasi perlu tindakan"/);
  assert.match(notificationCenterSource, /aria-label="Senarai notifikasi perlu tindakan"/);
  assert.match(notificationCenterSource, /aria-label=\{`Buang notifikasi: \$\{entry\.title\}`\}/);
  assert.match(notificationCenterSource, /role="tablist"/);
  assert.match(notificationCenterSource, /aria-label="Tapis notifikasi"/);
  assert.match(notificationCenterSource, /role="tabpanel"/);
  assert.match(notificationCenterSource, /getAriaSelectedProps\(selected\)/);
  assert.doesNotMatch(notificationCenterSource, /aria-selected=\{[^}]+\}/);
  assert.match(notificationCenterSource, /aria-label="Ringkasan notifikasi"/);
  assert.match(notificationCenterSource, /groupNotificationEntriesByModule/);
  assert.match(notificationCenterSource, /NOTIFICATION_CENTER_RENDER_LIMIT = NOTIFICATION_HISTORY_LIMIT/);
  assert.match(notificationCenterSource, /visibleEntries\.slice\(0, NOTIFICATION_CENTER_RENDER_LIMIT\)/);
  assert.match(notificationCenterSource, /Notifikasi \$\{group\.module\}/);
  assert.match(notificationCenterSource, /entry\.action\.href/);
  assert.match(notificationCenterSource, /onMarkRead\(\)/);
  assert.match(navbarSource, /removeNotificationHistoryEntry/);
  assert.doesNotMatch(notificationCenterSource, /localStorage|sessionStorage|setInterval|setTimeout/);
  assert.match(navbarCombinedSource, /aria-label=\{`Buka menu pengguna untuk \$\{username\}`\}/);
  assert.match(navbarSource, /onCloseAutoFocus=\{restoreDesktopUserMenuFocus\}/);
  assert.match(navbarSource, /onCloseAutoFocus=\{restoreMobileUserMenuFocus\}/);
  assert.match(navbarSource, /onEscapeKeyDown=\{scheduleDesktopUserMenuTriggerFocus\}/);
  assert.match(navbarSource, /onEscapeKeyDown=\{scheduleMobileUserMenuTriggerFocus\}/);
  assert.match(navbarSource, /pendingFocusFramesRef/);
  assert.match(navbarSource, /navbarMountedRef/);
  assert.match(navbarSource, /clearPendingUserMenuFocusFrames\(\)/);
  assert.match(navbarSource, /window\.requestAnimationFrame\(\(\) => \{/);
  assert.match(navbarSource, /window\.cancelAnimationFrame\(frameHandle\)/);
  assert.doesNotMatch(navbarSource, /setTimeout\([^)]*focus|globalThis\.setTimeout/);
  assert.match(navbarSource, /if \(!navbarMountedRef\.current\) \{/);
  assert.match(navbarSource, /useEffect\(\(\) => \{\s*setMobileNavOpen\(false\)\s*\}, \[activeLocation\.pathname\]\)/);
  assert.match(navbarSource, /desktopUserMenuTriggerRef\.current\?\.focus\(\{ preventScroll: true \}\)/);
  assert.match(navbarCombinedSource, /\{\[\.\.\.username\]\[0\] \|\| ""\}/);
  assert.doesNotMatch(navbarSource, /window\.location/);
  assert.match(homeButtonSource, /aria-label="Utama"/);
  assert.match(homeButtonSource, />Utama<\/span>/);
  assert.match(homeButtonSource, /nav-home-pill !hidden lg:!inline-flex/);
  assert.match(desktopNavigationSource, /aria-label="Navigasi utama"/);
  assert.match(desktopNavigationSource, /getAriaCurrentPageProps\(isActive\)/);
  assert.match(desktopNavigationSource, /getAriaCurrentPageProps\(active\)/);
  assert.match(desktopNavigationSource, /getAriaCurrentPageProps\(activeItem\)/);
  assert.doesNotMatch(desktopNavigationSource, /aria-current=\{[^}]+\}/);
  assert.match(desktopNavigationSource, /onEscapeKeyDown=\{\(\) => \{/);
  assert.match(desktopNavigationSource, /onCloseAutoFocus=\{\(event\) => \{/);
  assert.match(desktopNavigationSource, /groupTriggerRefs\.current\.get\(groupId\)\?\.focus\(\{ preventScroll: true \}\)/);
  assert.match(desktopNavigationSource, /scheduleGroupTriggerFocus\(group\.id\)/);
  assert.match(desktopNavigationSource, /pendingGroupFocusFramesRef/);
  assert.match(desktopNavigationSource, /clearPendingGroupTriggerFocusFrames\(\)/);
  assert.match(desktopNavigationSource, /window\.requestAnimationFrame\(\(\) => \{/);
  assert.match(desktopNavigationSource, /window\.cancelAnimationFrame\(frameHandle\)/);
  assert.doesNotMatch(desktopNavigationSource, /setTimeout\([^)]*focus|globalThis\.setTimeout/);
  assert.match(desktopNavigationSource, /if \(!navMountedRef\.current\) \{/);
  assert.match(userMenuSource, /navbar-dropdown-content/);
  assert.match(navbarStyles, /\.navbar-dropdown-content\[data-state="closed"\]\s*\{[\s\S]*animation:\s*none/);
  assert.match(scrollHintSource, /hint = translate\("common\.horizontalScroll\.hint"\)/);
  assert.match(navbarStyles, /\.navbar-nav-shell\s*\{[\s\S]*overflow-y:\s*auto/);
  assert.match(navbarStyles, /\.navbar-nav-shell\s*\{[\s\S]*scrollbar-width:\s*thin/);
  assert.match(navbarStyles, /\.navbar-nav-shell\s*\{[\s\S]*scrollbar-color:\s*hsl\(var\(--muted-foreground\) \/ 0\.42\) transparent/);
  assert.match(navbarSource, /data-testid="button-toggle-sidebar"/);
  assert.match(navbarSource, /aria-label=\{sidebarCollapsed \? "Kembangkan navigasi" : "Kecilkan navigasi"\}/);
  assert.match(desktopNavigationSource, /collapsed \? <TooltipContent side="right">\{item\.label\}/);
  assert.match(desktopNavigationSource, /collapsed \? <TooltipContent side="right">\{group\.label\}/);
  assert.match(homeButtonSource, /collapsed \? <TooltipContent side="right">Utama/);
  assert.match(navbarStyles, /@media \(max-width: 640px\)/);
  assert.doesNotMatch(navbarStyles, /@media \(max-width: 319px\)/);
  assert.match(mobileNavigationSource, /<SheetTitle>Navigasi<\/SheetTitle>/);
  assert.match(mobileNavigationSource, /onCloseAutoFocus=\{onCloseAutoFocus\}/);
  assert.match(navbarSource, /ref=\{mobileNavigationTriggerRef\}/);
  assert.match(navbarSource, /onCloseAutoFocus=\{restoreMobileNavigationFocus\}/);
  assert.match(navbarSource, /mobileNavigationTriggerRef\.current\?\.focus\(\{ preventScroll: true \}\)/);
  assert.match(mobileNavigationSource, /Bahagian semasa:/);
  assert.match(mobileNavigationSource, /aria-label="Navigasi mudah alih"/);
  assert.match(mobileNavigationSource, /getAriaCurrentPageProps\(active\)/);
  assert.doesNotMatch(mobileNavigationSource, /aria-current=\{[^}]+\}/);
  assert.match(mobileNavigationSource, /bg-primary\/10 text-primary/);
  assert.match(mobileNavigationSource, /active \? "text-primary" : "text-muted-foreground"/);
  assert.match(mobileNavigationSource, /min-h-11 w-full/);
  assert.match(navbarStyles, /\.nav-pill\.nav-pill-active\s*\{[\s\S]*color:\s*hsl\(var\(--primary\)\);/);
  assert.match(navbarStyles, /\.user-menu-role\s*\{[\s\S]*color:\s*hsl\(var\(--muted-foreground\)\);/);
  assert.doesNotMatch(navbarCombinedSource, /Open user menu|Open navigation menu/);
  assert.doesNotMatch(desktopNavigationSource, /Primary navigation|Scroll for more/);
  assert.doesNotMatch(scrollHintSource, /Scroll for more/);
  assert.doesNotMatch(mobileNavigationSource, /Mobile navigation|Current section:/);
  assert.doesNotMatch(mobileNavigationSource, /border-primary\/35 bg-primary\/10 text-primary shadow-sm/);
});

test("mobile navigation releases its modal on desktop resize and restores a visible navigation control", () => {
  const source = readSource("Navbar.tsx");
  assert.match(source, /if \(!mobileNavOpen\) return/);
  assert.match(source, /window\.matchMedia\("\(min-width: 1024px\)"\)/);
  assert.match(source, /if \(desktop\.matches\) setMobileNavOpen\(false\)/);
  assert.match(source, /desktop\.addEventListener\("change", closeOnDesktop\)/);
  assert.match(source, /return \(\) => desktop\.removeEventListener\("change", closeOnDesktop\)/);
  assert.match(source, /\}, \[mobileNavOpen\]\)/);
  assert.match(source, /ref=\{desktopNavigationTriggerRef\}/);
  assert.match(source, /desktopNavigationTriggerRef\.current\?\.focus\(\{ preventScroll: true \}\)/);
  assert.match(source, /mobileNavigationTriggerRef\.current\?\.focus\(\{ preventScroll: true \}\)/);
  assert.doesNotMatch(source, /window\.onresize\s*=/);
});

test("mobile current-page badge uses a solid contrast pair instead of stacking translucent fills", () => {
  const source = readSource("NavbarMobileNavigation.tsx");
  const badge = source.match(/<span className="([^"]+)">\s*Semasa\s*<\/span>/)?.[1];
  assert.ok(badge);
  assert.match(badge, /(?:^|\s)bg-primary(?:\s|$)/);
  assert.match(badge, /(?:^|\s)text-primary-foreground(?:\s|$)/);
  assert.doesNotMatch(badge, /bg-primary\/|text-primary(?:\s|$)/);
  assert.match(source, /getAriaCurrentPageProps\(active\)/);
});

test("shared sheet opening and closing motion use the specified subtle 200ms duration", () => {
  const source = readSource("ui/sheet.tsx");
  assert.match(source, /data-\[state=closed\]:duration-200 data-\[state=open\]:duration-200/);
  assert.match(source, /bg-black\/80 duration-200/);
  assert.doesNotMatch(source, /duration-(?:300|500)/);
});
