import type { CollectionAdminGroup, CollectionStaffNickname } from "@/lib/api";
import type { PendingUngroup } from "@/pages/collection-nicknames/utils";

export type CollectionNicknameDialogRoleScope = "admin" | "user" | "both";

export interface CollectionNicknameDialogsProps {
  leaderOptions: CollectionStaffNickname[];
  createGroupOpen: boolean;
  createLeaderId: string;
  creatingGroup: boolean;
  changeLeaderOpen: boolean;
  changeLeaderId: string;
  savingLeader: boolean;
  addOpen: boolean;
  newNickname: string;
  newRoleScope: CollectionNicknameDialogRoleScope;
  addingNickname: boolean;
  editingNickname: CollectionStaffNickname | null;
  editValue: string;
  editRoleScope: CollectionNicknameDialogRoleScope;
  savingEdit: boolean;
  pendingDeactivate: CollectionStaffNickname | null;
  statusBusyId: string | null;
  pendingDeleteGroup: CollectionAdminGroup | null;
  deletingGroup: boolean;
  pendingDeleteNickname: CollectionStaffNickname | null;
  deletingNicknameId: string | null;
  pendingResetPassword: CollectionStaffNickname | null;
  resettingNicknameId: string | null;
  pendingUngroup: PendingUngroup | null;
  ungrouping: boolean;
  confirmSwitchOpen: boolean;
  onCreateGroupOpenChange: (open: boolean) => void;
  onCreateLeaderIdChange: (value: string) => void;
  onCreateGroup: () => void;
  onChangeLeaderOpenChange: (open: boolean) => void;
  onChangeLeaderIdChange: (value: string) => void;
  onSaveLeader: () => void;
  onAddOpenChange: (open: boolean) => void;
  onNewNicknameChange: (value: string) => void;
  onNewRoleScopeChange: (value: CollectionNicknameDialogRoleScope) => void;
  onCreateNickname: () => void;
  onEditingNicknameOpenChange: (open: boolean) => void;
  onEditValueChange: (value: string) => void;
  onEditRoleScopeChange: (value: CollectionNicknameDialogRoleScope) => void;
  onSaveEditNickname: () => void;
  onPendingDeactivateOpenChange: (open: boolean) => void;
  onConfirmDeactivate: () => void;
  onPendingDeleteGroupOpenChange: (open: boolean) => void;
  onConfirmDeleteGroup: () => void;
  onPendingDeleteNicknameOpenChange: (open: boolean) => void;
  onConfirmDeleteNickname: () => void;
  onPendingResetPasswordOpenChange: (open: boolean) => void;
  onConfirmResetPassword: () => void;
  onPendingUngroupOpenChange: (open: boolean) => void;
  onConfirmUngroup: () => void;
  onConfirmSwitchOpenChange: (open: boolean) => void;
  onConfirmSwitch: () => void;
}
